(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
	(begin (set! balance (- balance amount))
	       balance)
	"Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount)) balance)
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
	  ((eq? m 'deposit) deposit)
	  (else (error "Unknown request -- MAKE-ACCOUNT"
		       m))))
  dispatch)

;;(define (make-account2 init-amount)
;;  (let (___)
;;    (define (withdraw amount)
;;      (set! balance (- balance amount))
;;      balance)
;;    (define (deposit amount)
;;      (set! balance (+ balance amount))
;;      balance)
;;    (define (dispatch)
;;      (cond ((eq? msg 'withdraw) withdraw)
;;	    ((eq? msg 'deposit) deposit)))
;;    dispatch))

(define (make-account2 init-amount)
  (let ((balance init-amount))
    (lambda (amount) (if (and (eq? msg 'withdraw) (> amount balance)) "Insufficient funds"))
    (define (withdraw amount)
      (set! balance (- balance amount))
      balance)
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch msg)
      (cond
       ((eq? msg 'withdraw) withdraw)
       ((eq? msg 'deposit) deposit)
       ((eq? msg 'get-balance) get-balance)))
    (define (get-balance msg)
      balance)
    dispatch))
