(define (make-account balance)
  (let ((init-balance balance))
    (define (withdraw amount)
      (if (>= balance amount)
	  (begin (set! balance (- balance amount))
		 balance)
	  "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount)) balance)
    ;;(define (get-balance) balance)
    (define (dispatch m)
      (cond ((eq? m 'withdraw) withdraw)
	    ((eq? m 'deposit) deposit)
	    ((eq? m 'balance) balance)
	    ((eq? m 'init-balance) init-balance)
	    (else (error "Unknown request -- MAKE-ACCOUNT"
			 m))))
    dispatch))
